apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rahulkale1/node-hello.git'
    targetRevision: HEAD
    path: 'node-hello'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

